version: "3.3"
   
services:
  db:
    image: fampay
    environment:
      - POSTGRES_DB=postgres
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A fampay worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A fampay beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
